### ISSUE TITLE
Create release "alt_v1.0"

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/Fluvoxamine-Model#20]
@Yuri05 

Now the model is used in the qualification report and references this (upcoming) release.

**Comment by Yuri05** [comment]
@PavelBal If you want to change release title or description - let me know. Closing.

**Comment by PavelBal** [comment]
@Yuri05 Maybe add this to release description:

The presented PBPK model of fluvoxamine has been developed to be used in a PBPK Drug-DrugInteractions (DDI) network with fluvoxamine as an inhibitor of CYP2C19 and CYP1A2. This version has not been qualified for the use as CYP3A4 inhibitor.

**Comment by Yuri05** [comment]
done
